create table public.movies (
  "movieId" bigint not null,
  title character varying(255) not null,
  productioncountries json,
  productionyear integer,
  length integer,
  genre character varying(100),
  distributor character varying(100),
  language character varying(100),
  subtitles character varying(100),
  director character varying(255),
  actors json,
  description text,
  images json,
  youtubetrailers json,
  current boolean not null default true,
  "ageRating" integer,
  constraint movies_pkey primary key ("movieId")
);

create table public.auditoriums (
  "auditoriumId" bigint generated by default as identity not null,
  name text not null,
  constraint auditorium_pkey primary key ("auditoriumId")
);

create table public.users (
  "userId" bigint not null,
  username character varying(255) not null unique,
  password character varying(255) not null,
  email text not null unique,
  "created_At" timestamp with time zone not null default now(),
  role text not null default "user",
  constraint users_pkey primary key ("userId")
);

create table public."ticketTypes" (
  "ticketTypeid" bigint generated by default as identity not null,
  name text not null,
  price numeric not null,
  constraint "ticketTypes_pkey" primary key ("ticketTypeid")
);

create table public.events (
  "eventId" bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  name text not null,
  date date,
  current boolean not null default true,
  info text,
  constraint events_pkey primary key ("eventId")
);

create table public.showings (
  "showingId" bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  "movieId" integer not null,
  "auditoriumId" bigint not null,
  date date not null,
  "time" time with time zone not null,
  "eventId" integer,
  constraint showings_pkey primary key ("showingId"),
  constraint "showings_auditoriumId_fkey" foreign KEY ("auditoriumId") references auditoriums ("auditoriumId"),
  constraint "showings_eventId_fkey" foreign KEY ("eventId") references events ("eventId"),
  constraint "showings_movieId_fkey" foreign KEY ("movieId") references movies ("movieId")
);

create table public.seats (
  "seatId" bigint generated by default as identity not null,
  "seatsRow" bigint not null,
  "seatsNumber" bigint not null,
  "auditoriumId" bigint not null,
  constraint seats_pkey primary key ("seatId"),
  constraint "seats_auditoriumId_fkey" foreign KEY ("auditoriumId") references auditoriums ("auditoriumId")
);

create table public.bookings (
  "bookingId" bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  "bookingNumber" text not null,
  email text not null,
  "showingId" bigint not null,
  "userId" integer,
  constraint booking_pkey primary key ("bookingId"),
  constraint "booking_showingId_fkey" foreign KEY ("showingId") references showings ("showingId"),
  constraint "booking_userId_fkey" foreign KEY ("userId") references users ("userId")
);

create table public.tickets (
  "ticketId" bigint generated by default as identity not null,
  "ticketTypeId" bigint not null,
  "bookingId" bigint not null,
  "seatId" bigint not null,
  constraint tickets_pkey primary key ("ticketId"),
  constraint "tickets_bookingId_fkey" foreign KEY ("bookingId") references bookings ("bookingId"),
  constraint "tickets_seatId_fkey" foreign KEY ("seatId") references seats ("seatId"),
  constraint "tickets_ticketTypeId_fkey" foreign KEY ("ticketTypeId") references "ticketTypes" ("ticketTypeid")
);